//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inicio.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.TiempoMedioSoap")]
    public interface TiempoMedioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asignatura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dedicaciones", ReplyAction="*")]
        Inicio.Service.DedicacionesResponse Dedicaciones(Inicio.Service.DedicacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DedicacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dedicaciones", Namespace="http://tempuri.org/", Order=0)]
        public Inicio.Service.DedicacionesRequestBody Body;
        
        public DedicacionesRequest() {
        }
        
        public DedicacionesRequest(Inicio.Service.DedicacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DedicacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asignatura;
        
        public DedicacionesRequestBody() {
        }
        
        public DedicacionesRequestBody(string asignatura) {
            this.asignatura = asignatura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DedicacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DedicacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inicio.Service.DedicacionesResponseBody Body;
        
        public DedicacionesResponse() {
        }
        
        public DedicacionesResponse(Inicio.Service.DedicacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DedicacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double DedicacionesResult;
        
        public DedicacionesResponseBody() {
        }
        
        public DedicacionesResponseBody(double DedicacionesResult) {
            this.DedicacionesResult = DedicacionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiempoMedioSoapChannel : Inicio.Service.TiempoMedioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiempoMedioSoapClient : System.ServiceModel.ClientBase<Inicio.Service.TiempoMedioSoap>, Inicio.Service.TiempoMedioSoap {
        
        public TiempoMedioSoapClient() {
        }
        
        public TiempoMedioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiempoMedioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiempoMedioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiempoMedioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inicio.Service.DedicacionesResponse Inicio.Service.TiempoMedioSoap.Dedicaciones(Inicio.Service.DedicacionesRequest request) {
            return base.Channel.Dedicaciones(request);
        }
        
        public double Dedicaciones(string asignatura) {
            Inicio.Service.DedicacionesRequest inValue = new Inicio.Service.DedicacionesRequest();
            inValue.Body = new Inicio.Service.DedicacionesRequestBody();
            inValue.Body.asignatura = asignatura;
            Inicio.Service.DedicacionesResponse retVal = ((Inicio.Service.TiempoMedioSoap)(this)).Dedicaciones(inValue);
            return retVal.Body.DedicacionesResult;
        }
    }
}
